futu:
  host: 127.0.0.1
  port: 11111
  ktype: K_1M
  autype: qfq
  symbol: US.AAPL
symbols:
  - US.AAPL

alerts:
  enabled: false
  throttle_seconds: 60
  min_unrealized_pnl: -200     # 触发PnlDrop告警阈值
  min_voter_score: -1.0        # 触发ScoreTooLow告警阈值
  telegram:
    bot_token: ""
    chat_id: ""
  email:
    smtp_host: "smtp.example.com"
    smtp_port: 587
    username: ""
    password: ""
    from_addr: "bot@example.com"
    to_addrs: ["you@example.com"]
